---

- name: Add user gomud
  ansible.builtin.user:
    name: "{{ user }}"
    comment: applicative user
    create_home: true
    state: present
    shell: /bin/bash

- name: Copy ssh key
  ansible.posix.authorized_key:
    user: "{{ user }}"
    exclusive: true
    key: "https://github.com/{{ item }}.keys"
    state: present
  with_items:
    - "{{ github_users }}"



- name: Copie systemd service file
  ansible.builtin.copy:
    src: gomud.service
    dest: /etc/systemd/system/gomud.service
    mode: "0644"

- name: Activate service at start
  ansible.builtin.systemd_service:
    enabled: true
    state: started
    name: gomud
    daemon_reload: true
